camera_node:
  ros__parameters:
    width: 640
    height: 360
    fps: 30.0
    pixel_format: "YUYV"
    auto_fallback_devices: true
    required_name_substring: "C920"
    left:
      device: "/dev/video4"
      frame_id: "camera_left"
      image_topic: "/camera/left/image_raw"
      camera_info_topic: "/camera/left/camera_info"
      camera_info: "~/.ros/camera_info/c920_left.yaml"
    right:
      device: "auto"
      frame_id: "camera_right"
      image_topic: "/camera/right/image_raw"
      camera_info_topic: "/camera/right/camera_info"
      camera_info: "~/.ros/camera_info/c920_right.yaml"
