ultrasonic_node:
  ros__parameters:
    port: "/dev/ttyACM0"
    baudrate: 115200
    sensor_names: ["front", "left", "right"]
    frame_prefix: "ultrasonic_"
    field_of_view: 0.26
    min_range: 0.02
    max_range: 4.0
    publish_timeout: 0.5
